source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PodsTutorial_Example', :exclusive => true do
  pod "PodsTutorial", :path => "../"
end

target 'PodsTutorial_Tests', :exclusive => true do
  pod "PodsTutorial", :path => "../"

  
end
